import { InMemoryDbService } from 'angular-in-memory-web-api';

export class InMemoryDataService implements InMemoryDbService {
  createDb() {
    const notes = [
      { id: 1, name: 'Occaecat esse', content: 'Cillum ad reprehenderit ipsum magna sit Lorem elit. Esse cupidatat consequat ut Lorem reprehenderit mollit aute fugiat amet. Esse voluptate magna non officia ipsum esse labore officia id laboris. Esse nostrud proident labore do Lorem ut ipsum aliquip aliquip officia tempor. Consequat ut qui est sunt anim fugiat ullamco tempor magna.' },
      { id: 2, name: 'Irure cupidatat', content: 'Exercitation velit pariatur ad occaecat ipsum dolor. Minim sunt labore ea reprehenderit esse occaecat cillum ipsum laborum. Nisi aliqua et anim Lorem voluptate nisi incididunt in duis mollit cupidatat qui proident. Et qui in reprehenderit fugiat laborum culpa velit laborum officia. Culpa cillum enim aute consectetur ex labore excepteur Lorem. Consequat aliqua veniam sint irure aliqua qui velit cupidatat.' },
      { id: 3, name: 'Dolor esse', content: 'Commodo magna proident consequat consequat duis fugiat labore cillum ipsum commodo exercitation irure cupidatat. Voluptate nostrud nisi labore ea reprehenderit eiusmod culpa nisi in anim quis ea ex. Ullamco labore incididunt et sunt nulla dolor veniam. Sint sint aliqua nisi aliquip laboris duis officia. Ex consequat ad sint labore. Voluptate voluptate do nisi est est labore aliquip est qui. Cupidatat anim laboris ipsum nulla in consectetur consequat ea qui laborum incididunt.' },
      { id: 4, name: 'Lorem in', content: 'Proident ut voluptate id adipisicing Lorem occaecat id ipsum labore minim. Culpa incididunt elit non incididunt ex elit aliqua consectetur. Consectetur quis ea est anim fugiat adipisicing fugiat.' },
      { id: 5, name: 'Culpa voluptate', content: 'Incididunt elit ea pariatur eiusmod exercitation. Laboris esse exercitation veniam cupidatat qui officia esse incididunt velit aliqua anim. Incididunt enim Lorem laboris enim. Consequat sunt pariatur id ullamco in. Cupidatat sint eiusmod voluptate ea amet duis sunt officia quis mollit id non.' },
      { id: 6, name: 'Laborum nostrud', content: 'Nulla commodo ut eiusmod commodo ullamco nulla sit mollit. Irure veniam esse occaecat labore ex excepteur in duis sint aute velit qui. Ut Lorem id in ullamco ipsum reprehenderit nisi do eu esse. Minim ullamco culpa mollit in veniam anim aliquip duis occaecat deserunt laborum. Amet culpa minim fugiat cillum pariatur mollit proident irure minim cupidatat veniam eiusmod proident. Voluptate sunt cillum commodo voluptate ea occaecat enim anim aliqua dolor cillum.' },
      { id: 7, name: 'Nostrud ex', content: 'Ea sit aute cillum voluptate ad consectetur reprehenderit dolor deserunt anim dolore magna deserunt magna. In duis laboris nostrud tempor aute esse do in labore aute amet consectetur. Qui sunt dolor proident ea et in excepteur eu qui deserunt nulla ea aute. Ullamco consectetur reprehenderit do nulla ad incididunt aliqua laboris in minim. Sunt incididunt do consequat mollit ipsum qui est veniam laboris incididunt. Pariatur nostrud aute cupidatat tempor commodo mollit sit duis mollit. Officia minim ipsum incididunt enim nostrud nulla eiusmod nisi.' },
      { id: 8, name: 'Magna anim', content: 'Ipsum adipisicing quis laboris sunt ut consectetur amet. Esse proident irure minim nostrud enim anim ipsum ea tempor proident adipisicing esse incididunt id. Nisi quis reprehenderit labore commodo veniam sint nulla nulla cupidatat elit adipisicing adipisicing ut. Anim non excepteur id commodo velit consequat nostrud. Aliqua voluptate minim deserunt minim consequat tempor laborum. Quis officia adipisicing consequat magna sunt irure laborum.' },
      { id: 9, name: 'Sunt labore', content: 'Elit aliqua pariatur id incididunt laborum. Incididunt officia qui eiusmod quis aliquip ullamco minim nisi pariatur voluptate. Aliquip ex laborum nostrud aliqua quis et qui tempor et in voluptate sint. Adipisicing aliquip consequat in ipsum proident.' },
      { id: 10, name: 'Ad laboris', content: 'Officia ut sit dolor in. Minim proident deserunt ex consequat Lorem ea. Laborum tempor nostrud voluptate deserunt exercitation. Dolore in velit laborum ut ea incididunt officia. Ullamco quis ad laboris consequat ut. Exercitation veniam sit anim aliqua commodo id.' }
    ];
    return { notes };
  }
}
